Extend trenzn
anetz89/bayrischer_schmaaz pull request #1
Opened 2023-04-24 18:27 UTC by BenjaminBrandmeier

This PR extends the meaning of trenzn. 

Additionally a real-world example sentence including the word trenzn is included.

2023-06-07 19:38 UTC, anetz89 commented on bayrischer_schmaaz.csv
> +trenzn,"weinen, schluchzen oder etwas verschütten",Hosd di scho wida o'trenzd du Fagge!
please add a comma in front of 'oder'

2023-06-07 19:40 UTC, anetz89 requested changes
overall a great commit, but I would have expected correct grammar

2023-06-08 04:00 UTC, BenjaminBrandmeier commented on bayrischer_schmaaz.csv
> +trenzn,"weinen, schluchzen oder etwas verschütten",Hosd di scho wida o'trenzd du Fagge!
Absolutely!

2023-06-09 19:44 UTC, anetz89 approved these changes
soidad jetz bassn ;)
wobei zwoa zeilen vll schena warn...

2023-06-09 21:05 UTC, anetz89 commented
weils wuaschd is

2023-06-09 21:05 UTC, merged